#!/bin/bash

checkparams() {
    if [ $# -eq 0 ]; then
        echo "Please specify the device path (e.g. /dev/sdb)" >&2
        exit 1
    fi

    # If you want to work on something else than a block device, such as a
    # `.img` file, remove the check below.
    if [ ! -b $1 ]; then
        echo "$1 is not a valid target device" >&2
        exit 1
    fi
}

getpassword() {
    local PW=$(systemd-ask-password "Enter your password:")
    if [ -z "$PW" ]; then
        echo "Please provide a password" >&2
        exit 1
    fi
    echo $PW
}

checkpassword() {
    local PW=$1
    local PWCHECK=$(systemd-ask-password "Verify password:")

    if [ "$PW" != "$PWCHECK" ]; then
        echo "Passwords do not match" >&2
        exit 1
    fi
}

getkey() {
    local PW=$1
    CHALLENGE=$(printf $PW | sha256sum | awk '{print $1}')
    echo "Touch your YubiKey" > /dev/tty
    RESPONSE=$(ykchalresp -2 $CHALLENGE)

    echo $CHALLENGE$RESPONSE
}
