#!/bin/bash

set -e

# This expects to find the `util` file that is included in the repository. You
# will either have to clone the whole repository or manually place the file
# here.
source ./util --source-only

DEV=$1
checkparams $DEV

echo "First provide your old password"
PW=$(getpassword)
OLDKEY=$(getkey "$PW")

echo "Now enter the new one"
PW=$(getpassword)
checkpassword "$PW"
NEWKEY=$(getkey "$PW")

# The command below will add the $NEWKEY in key slot 1. If it is already taken,
# adjust the command accordingly. `cryptsetup luksDump "$DEV"` can help you to
# inspect key slots.
echo "Adding new key..."
printf '%s\n' "$OLDKEY" "$NEWKEY" "$NEWKEY" | \
    sudo cryptsetup luksAddKey --key-slot=1 "$DEV"
