#!/bin/bash

set -e

source ./util --source-only

DEV=$1
checkparams $DEV

echo "Warning: this script will format and encrypt the device you specified. All data on the device will be irrecoverably lost."

PW=$(getpassword)
checkpassword $PW

KEY=$(getkey "$PW")

echo "Encrypting device"
sudo cryptsetup -v luksFormat $DEV <<<$KEY
