#!/bin/bash

set -e

source ./util --source-only

checkparams $1

echo "Warning: this script will format and encrypt the device you specified. All data on the device will be irrecoverably lost."

getkey

echo "Encrypting device"
sudo cryptsetup -v luksFormat $1 <<<$KEY
